table Sample_Table_Sales
	lineageTag: 9b3ec1c8-9971-4451-a1e0-8e8efb5ec0de

	column 'Sale ID'
		dataType: int64
		formatString: 0
		lineageTag: 2a293880-ec33-44f3-ba47-9931710bb8cf
		summarizeBy: count
		sourceColumn: Sale ID

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 024436bb-a85a-49ae-986e-c529328d641d
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: 102720ec-3478-497d-a1f5-e21323b3a83e
			defaultHierarchy: LocalDateTable_ffbda448-3aa2-4912-b1cb-bb6c32be2b4b.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Region
		dataType: string
		lineageTag: be1e448b-e4fa-485d-b8a0-ad161bda4878
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: string
		lineageTag: 46ea6740-d2d2-4caa-a5af-1a34a20a83c8
		summarizeBy: none
		sourceColumn: Product ID

		annotation SummarizationSetBy = Automatic

	column 'Units Sold'
		dataType: int64
		formatString: 0
		lineageTag: 1a3ef726-8593-48a5-8518-5258594d4c62
		summarizeBy: sum
		sourceColumn: Units Sold

		annotation SummarizationSetBy = Automatic

	column 'Unit Price'
		dataType: int64
		formatString: 0
		lineageTag: 722dae9f-b071-4d13-bd21-21cf1b8faae9
		summarizeBy: sum
		sourceColumn: Unit Price

		annotation SummarizationSetBy = Automatic

	column Revenue
		dataType: int64
		formatString: 0
		lineageTag: 53f652ca-dcda-4b67-beea-22e73cc74a34
		summarizeBy: sum
		sourceColumn: Revenue

		annotation SummarizationSetBy = Automatic

	partition Sample_Table_Sales = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("bc6xCsMgEAbgd7k5gfPOi+naPVDoKBka6lAoKaRkyNvX00iDZBE9/fx/78FAA4QkLboW9TCE9/RZlznE/Q3TyBDqK4kLIyKMjQeq3X17zmHLSC/7/DxByYaPhs6zLlKiiJ0kZmt2XV7f6VGU/tppjk1hdi8oR8UnBY3B0pB5R12NqoY6cv+sXtn4Aw==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Sale ID" = _t, Date = _t, Region = _t, #"Product ID" = _t, #"Units Sold" = _t, #"Unit Price" = _t, Revenue = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Sale ID", Int64.Type}, {"Date", type date}, {"Region", type text}, {"Product ID", type text}, {"Units Sold", Int64.Type}, {"Unit Price", Int64.Type}, {"Revenue", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

