table TestTable
	lineageTag: 386ee3d7-b940-4e07-bbde-99028c6cc8a8

	column Number
		dataType: int64
		formatString: 0
		lineageTag: 5a066097-9860-4ecf-98c7-ecfac72ca13f
		summarizeBy: sum
		sourceColumn: Number

		annotation SummarizationSetBy = Automatic

	column Column1
		dataType: string
		lineageTag: ef666b61-6488-4742-ace9-742bacd5259e
		summarizeBy: none
		sourceColumn: Column1

		annotation SummarizationSetBy = Automatic

	partition TestTable = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlTSUVKK1YlWMoIxjGEMExjDFMyIBQA=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Number = _t, Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Number", Int64.Type}, {"Column1", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

